var elementorFrontendConfig = {
  environmentMode: {
    edit: false,
    wpPreview: false,
    isScriptDebug: false,
  },
  i18n: {},
  is_rtl: false,
  breakpoints: {
    xs: 0,
    sm: 480,
    md: 768,
    lg: 1025,
    xl: 1440,
    xxl: 1600,
  },
  responsive: {
    breakpoints: {
      mobile: {
        label: "Mobile Portrait",
        value: 767,
        default_value: 767,
        direction: "max",
        is_enabled: true,
      },
      mobile_extra: {
        label: "Mobile Landscape",
        value: 880,
        default_value: 880,
        direction: "max",
        is_enabled: false,
      },
      tablet: {
        label: "Tablet Portrait",
        value: 1024,
        default_value: 1024,
        direction: "max",
        is_enabled: true,
      },
      tablet_extra: {
        label: "Tablet Landscape",
        value: 1200,
        default_value: 1200,
        direction: "max",
        is_enabled: false,
      },
      laptop: {
        label: "Laptop",
        value: 1366,
        default_value: 1366,
        direction: "max",
        is_enabled: false,
      },
      widescreen: {
        label: "Widescreen",
        value: 2400,
        default_value: 2400,
        direction: "min",
        is_enabled: false,
      },
    },
    hasCustomBreakpoints: false,
  },
  version: "3.28.4",
  is_static: false,
  experimentalFeatures: {
    e_font_icon_svg: true,
    additional_custom_breakpoints: true,
    container: true,
    e_local_google_fonts: true,
    "hello-theme-header-footer": true,
    "nested-elements": true,
    editor_v2: true,
    e_element_cache: true,
    home_screen: true,
  },
  urls: {
    assets: "https://templates.kohesifstudio.com/",
  },
  nonces: {
    floatingButtonsClickTracking: "7ec6b9889a",
  },
  swiperClass: "swiper",
  settings: {
    page: [],
    editorPreferences: [],
  },
  kit: {},
  post: {},
};
